# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Runs a set of commands using the runners shell
      - name: Upgrade distribution modules
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a set of commands using the runners shell
      - name: Install build dependencies
        run: |
          pip install --upgrade wheel
          pip install --upgrade numpy

      # Runs a set of commands using the runners shell
      - name: Print python info
        run: |
           python ./ci/info_platform.py
           pip list

      # Runs a set of commands using the runners shell
      - name: Generate source package or wheel
        run: |
          python setup.py sdist
          ls dist

      - name: Install from source package
        run:
          pip install --pre --find-links dist/ --no-cache-dir --no-index fisx

      - name: Run the tests
        run:
          python -m fisx.tests.testAll

